DROP TABLE IF EXISTS users;
CREATE TABLE users (
id INTEGER PRIMARY KEY AUTOINCREMENT,
name TEXT NOT NULL,
email TEXT NOT NULL UNIQUE,
password TEXT NOT NULL
);

DROP TABLE IF EXISTS friends;
CREATE TABLE friends (
name TEXT NOT NULL,
friend TEXT NOT NULL,
);
